project:
  name: VRisingServer
  version: 1.0.0
  description: Create a development environment for V Rising Server Project
container:
  build: |
    FROM ubuntu:latest

    RUN apt-get update && apt-get install wget zip apt-transport-https ca-certificates gnupg curl python3-pip -y

    RUN pip3 install google-auth --break-system-packages

    RUN apt install openssh-server -y && \
        systemctl enable ssh

    RUN apt-get install software-properties-common -y && \
        add-apt-repository --yes --update ppa:ansible/ansible && \
        apt-get install ansible -y 
        
    RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
        curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg && \
        apt-get update && apt-get install google-cloud-sdk -y
    

    RUN wget https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_amd64.zip && \
        unzip terraform_1.3.7_linux_amd64.zip && \
        mv terraform /usr/bin && \
        rm -f terraform_1.3.7_linux_amd64.zip

auto-stop: true