---
- name: Copy your local save to Server
  hosts: vm-v-rising-server
  connection: ssh
  gather_facts: false
  remote_user: root
  become_method: sudo
  become: yes

  tasks:
    - name: Copy file to destination
      copy:
        src: ../misc/vrising-local-saves/v3/
        dest: /root/vrising/persistentdata/Saves/v3/