services:
  vrising:
    image: trueosiris/vrising
    environment:
      - TZ=America/Sao_Paulo
      - SERVERNAME=Vampiroca
    volumes:
      - type: bind
        source: /root/vrising/server
        target: /mnt/vrising/server
        bind:
          create_host_path: true
      - type: bind
        source: /root/vrising/persistentdata
        target: /mnt/vrising/persistentdata
        bind:
          create_host_path: true
    ports:
      - '9876:9876/udp'
      - '9877:9877/udp'
    restart: unless-stopped
    network_mode: bridge
